name: 'Deploy'
description: 'Deploy a server'
inputs:
  ssh-key:
    description: 'Content of the private SSH key'
    required: true
  ssh-connection:
    description: 'SSH connection string'
    required: true
  image-tag:
    description: 'Docker image tag'
    required: true
  aws-access-key:
    description: 'AWS access key'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-default-region:
    description: 'AWS default region'
    required: true
  aws-bucket:
    description: 'AWS bucket name'
    required: true
  db-user:
    description: 'DB user'
    required: true
  db-password:
    description: 'DB password'
    required: true
  app-key:
    description: 'App key'
    required: true
  app-env:
    description: 'App env'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Copy SSH key
      run: |
        echo "${{ inputs.ssh-key }}" >> ./id_rsa
        chmod 600 id_rsa
      shell: bash
    - name: Deploy app
      run: |
        scp -v -C -o StrictHostKeyChecking=no -i ./id_rsa ./deployment/bin/deploy.sh ${{ inputs.ssh-connection }}:/home/apprunner/deploy.sh
        scp -v -C -o StrictHostKeyChecking=no -i ./id_rsa ./docker-compose.prod.yml ${{ inputs.ssh-connection }}:/usr/src/docker-compose.prod.yml
        scp -v -C -o StrictHostKeyChecking=no -i ./id_rsa ./.env.prod.template ${{ inputs.ssh-connection }}:/usr/src/.env
        ssh -v -tt -o StrictHostKeyChecking=no -i ./id_rsa ${{ inputs.ssh-connection }} "chmod +x /home/apprunner/deploy.sh"
        ssh -v -tt -o StrictHostKeyChecking=no -i ./id_rsa ${{ inputs.ssh-connection }} "
          sed -i "/IMAGE_TAG/c\IMAGE_TAG=${{ inputs.image-tag }}" /usr/src/.env
        
          sed -i "/AWS_ACCESS_KEY_ID/c\AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key }}" /usr/src/.env
          sed -i "/AWS_SECRET_ACCESS_KEY/c\AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}" /usr/src/.env
          sed -i "/AWS_BUCKET/c\AWS_BUCKET=${{ inputs.aws-bucket }}" /usr/src/.env
          sed -i "/AWS_DEFAULT_REGION/c\AWS_DEFAULT_REGION=${{ inputs.aws-default-region }}" /usr/src/.env
        
          sed -i "/DB_USER/c\DB_USER=${{ inputs.db-user }}" /usr/src/.env
          sed -i "/DB_PASSWORD/c\DB_PASSWORD=${{ inputs.db-password }}" /usr/src/.env
        
          sed -i "/APP_KEY/c\APP_KEY=${{ inputs.app-key }}" /usr/src/.env
          sed -i "/APP_ENV/c\APP_ENV=${{ inputs.app-env }}" /usr/src/.env"
        ssh -v -tt -o StrictHostKeyChecking=no -i ./id_rsa ${{ inputs.ssh-connection }} "/home/apprunner/deploy.sh"
      shell: bash
