name: 'Deploy'
description: 'Deploy a server'
inputs:
  ssh-key:
    description: 'Content of the private SSH key'
    required: true
  ssh-connection:
    description: 'SSH connection string'
    required: true
  image-tag:
    description: 'Docker image tag'
    required: true
  aws-acces-key:
    description: 'AWS access key'
    required: true
  aws-secret-acces-key:
    description: 'AWS secret access key'
    required: true
  aws-bucket:
    description: 'AWS bucket name'
    required: true
  db-password:
    description: 'DB password'
    required: true
  app-key:
    description: 'App key'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo "${{ inputs.ssh-key }}" >> ./id_rsa
        chmod 600 id_rsa
      shell: bash
    - run: |
        scp -C -o StrictHostKeyChecking=no -i ./id_rsa ./deployment/bin/deploy.sh ${{ inputs.ssh-connection }}:/home/martin/deploy.sh
        scp -C -o StrictHostKeyChecking=no -i ./id_rsa ./docker-compose.prod.yml ${{ inputs.ssh-connection }}:/usr/src/docker-compose.prod.yml
        scp -C -o StrictHostKeyChecking=no -i ./id_rsa ./.env.prod.template ${{ inputs.ssh-connection }}:/usr/src/.env
        ssh -tt -o StrictHostKeyChecking=no -i ./id_rsa ${{ inputs.ssh-connection }} "chmod +x /home/martin/deploy.sh"
        ssh -tt -o StrictHostKeyChecking=no -i ./id_rsa ${{ inputs.ssh-connection }} "
          sed -i "/IMAGE_TAG/c\IMAGE_TAG=${{ inputs.image-tag }}" /usr/src/.env

          sed -i "/AWS_ACCESS_KEY_ID/c\AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key }}" /usr/src/.env
          sed -i "/AWS_SECRET_ACCESS_KEY/c\AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}" /usr/src/.env
          sed -i "/AWS_BUCKET/c\AWS_BUCKET=${{ inputs.aws-bucket }}" /usr/src/.env

          sed -i "/DB_PASSWORD/c\DB_PASSWORD=${{ inputs.db-password }}" /usr/src/.env

          sed -i "/APP_KEY/c\APP_KEY=${{ inputs.app-key }}" /usr/src/.env"
        ssh -tt -o StrictHostKeyChecking=no -i ./id_rsa ${{ inputs.ssh-connection }} "/home/martin/deploy.sh"
      shell: bash
