version: "2.4"
services:
  api:
    image: ${API_IMAGE}
    environment:
      - APP_NAME=posts
      - APP_ENV=local
      - APP_KEY=base64:aL6o/U2e1ziUTXsyTkfzNziH9l4crCISoWMwC8LX4B0=
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-test
      - DB_PORT=3306
      - DB_DATABASE=posts
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=sync
      - MAIL_MAILER=log
    depends_on:
      migrate:
        condition: service_started
      mysql-test:
        condition: service_healthy

  mysql-test:
    image: ${MYSQL_IMAGE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  migrate:
    image: ${API_IMAGE}
    environment:
      - APP_ENV=local
      - APP_KEY=base64:aL6o/U2e1ziUTXsyTkfzNziH9l4crCISoWMwC8LX4B0=
      - APP_DEBUG=true
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-test
      - DB_PORT=3306
      - DB_DATABASE=posts
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      mysql-test:
        condition: service_healthy
