version: "2.4"
services:
  api:
    image: ${API_IMAGE}
    environment:
      - APP_NAME=posts
      - APP_KEY=base64:aL6o/U2e1ziUTXsyTkfzNziH9l4crCISoWMwC8LX4B0=
    depends_on:
      migrate:
        condition: service_started
      mysql-test:
        condition: service_healthy

  mysql-test:
    image: ${MYSQL_IMAGE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  migrate:
    image: ${API_IMAGE}
    environment:
      - APP_NAME=posts
      - APP_KEY=base64:aL6o/U2e1ziUTXsyTkfzNziH9l4crCISoWMwC8LX4B0=
    depends_on:
      mysql-test:
        condition: service_healthy
