# Use the up.sh to run this stack. It uses the production images on your local machine.
version: "3.8"
services:
  frontend:
    build:
      args:
        API_BASE_URL: http://localhost:8000
      context: .
      dockerfile: ./frontend/Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - ./frontend:/usr/src
    environment:
      - NODE_ENV=local
      - API_BASE_URL=http://localhost:8000

  api:
    image: martinjoo/posts-api:${IMAGE_TAG}
    command: sh -c "./wait-for-it.sh mysql:3306 -t 30 && ./wait-for-it.sh redis:6379 -t 30 && php-fpm"
    restart: unless-stopped
    volumes:
      - ./api/app:/usr/src/app
      - ./api/config:/usr/src/config
      - ./api/database:/usr/src/database
      - ./api/routes:/usr/src/routes
      - ./api/storage:/usr/src/storage
      - ./api/tests:/usr/src/tests
      - .env:/usr/src/.env
      - ./deployment/config/php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - migrate
      - mysql
      - redis

  scheduler:
    image: martinjoo/posts-scheduler:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./api/app:/usr/src/app
      - ./api/config:/usr/src/config
      - ./api/database:/usr/src/database
      - ./api/routes:/usr/src/routes
      - ./api/storage:/usr/src/storage
      - ./api/tests:/usr/src/tests
      - .env:/usr/src/.env
    depends_on:
      - migrate
      - mysql
      - redis

  worker:
    image: martinjoo/posts-worker:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./api/app:/usr/src/app
      - ./api/config:/usr/src/config
      - ./api/database:/usr/src/database
      - ./api/routes:/usr/src/routes
      - ./api/storage:/usr/src/storage
      - ./api/tests:/usr/src/tests
      - .env:/usr/src/.env
    depends_on:
      - migrate
      - mysql
      - redis

  nginx:
    image: martinjoo/posts-nginx:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./api:/usr/src
      - ./deployment/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - api

  mysql:
    image: martinjoo/posts-mysql:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
    ports:
      - "63790:6379"

  migrate:
    image: martinjoo/posts-api:${IMAGE_TAG}
    command: sh -c "./wait-for-it.sh mysql:3306 -t 30 && php /usr/src/artisan migrate --force"
    restart: no
    volumes:
      - .env:/usr/src/.env
    depends_on:
      - mysql
