name: CI/CD Workflow  # Ativado ao abrir PR e atualizar PR aberto

on:
  pull_request: # qualquer branch ao abrir PR ou atualizar o PR
    types: [ opened, synchronize ]

env:
  API_IMAGE: rcarlos/devops-with-laravel-api:${{ github.sha }}
  SCHEDULER_IMAGE: rcarlos/devops-with-laravel-scheduler:${{ github.sha }}
  WORKER_IMAGE: rcarlos/devops-with-laravel-worker:${{ github.sha }}
  NGINX_IMAGE: rcarlos/devops-with-laravel-nginx:${{ github.sha }}
  PROXY_IMAGE: rcarlos/devops-with-laravel-proxy:${{ github.sha }}
  MYSQL_IMAGE: rcarlos/devops-with-laravel-database:${{ github.sha }}
  FRONTEND_IMAGE: rcarlos/devops-with-laravel-frontend:${{ github.sha }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  analyze-code:
    name: Analyze Code
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.event.pull_request.base.ref == 'main' && 'prod') || (github.event.pull_request.base.ref == 'develop' && 'staging') }}
    steps:
      - uses: actions/checkout@v3
      - name: Build API Image
        run: docker build -t $API_IMAGE --target=api -f ./api/Dockerfile .
      - name: Run phpstan
        run: docker run --rm -t $API_IMAGE ./vendor/bin/phpstan analyze --memory-limit=1G
      - name: Run phpinsights
        run: docker run --rm -t $API_IMAGE php artisan insights --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90 --ansi --format=github-action

  test-code:
    name: Test Code
    needs: [ analyze-code]
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.event.pull_request.base.ref == 'main' && 'prod') || (github.event.pull_request.base.ref == 'develop' && 'staging') }}
    steps:
      - uses: actions/checkout@v3
      - name: Build API Image
        run: docker build -t $API_IMAGE --target=api -f ./api/Dockerfile .
      - name: Build MySQL Image
        run: docker build -t $MYSQL_IMAGE --build-arg password=${{ secrets.DB_PASSWORD }} -f ./Dockerfile.mysql .
      - name: Run tests
        run: |
          docker run --rm -t $API_IMAGE php artisan test