name: Pull request

on:
  pull_request:
    branches: [ "main" ]

env:
  API_IMAGE: martinjoo/posts-api:${{ github.sha }}
  SCHEDULER_IMAGE: martinjoo/posts-scheduler:${{ github.sha }}
  WORKER_IMAGE: martinjoo/posts-worker:${{ github.sha }}
  NGINX_IMAGE: martinjoo/posts-nginx:${{ github.sha }}
  PROXY_IMAGE: martinjoo/posts-proxy:${{ github.sha }}
  MYSQL_IMAGE: martinjoo/posts-mysql:${{ github.sha }}
  FRONTEND_IMAGE: martinjoo/posts-frontend:${{ github.sha }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: ./.github/workflows/jobs/build-backend-images
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build MySQL image
        run: |
          docker build -t $MYSQL_IMAGE --build-arg password=${{ secrets.DB_PASSWORD }} -f ./Dockerfile.mysql .
      - uses: ./.github/workflows/jobs/analyze
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: ./.github/workflows/jobs/test
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
